"""Tests for configuration loading and generated files."""

from __future__ import annotations

from pathlib import Path

import pytest

from codex_cli_sync.config import Config
from codex_cli_sync.errors import ConfigError


def test_defaults_exclude_auth_transient_and_local_runtime_files() -> None:
    """Verify defaults keep machine-local runtime artifacts out of sync."""
    config = Config()
    gitignore = config.render_gitignore()

    required_patterns = """
    auth.json
    .sync.lock
    .sync.log
    log/
    models_cache.json
    logs_*.sqlite*
    state_*.sqlite*
    context-mode/content/
    shell_snapshots/
    tmp/
    *.sqlite-wal
    *.sqlite-shm
    *.db-wal
    *.db-shm
    """.split()
    for pattern in required_patterns:
        assert pattern in gitignore

    assert "sessions/" not in gitignore
    assert "history.jsonl" not in gitignore
    assert config.render_gitattributes() == ""


def test_lfs_attributes_are_opt_in() -> None:
    """Verify Git LFS attributes are only emitted when configured."""
    config = Config(lfs_patterns=["sessions/**"])
    assert "sessions/** filter=lfs" in config.render_gitattributes()


def test_load_user_overrides(tmp_path: Path) -> None:
    """Verify user TOML values override default config."""
    (tmp_path / ".sync.toml").write_text("""
[sync]
auto_pull_on_start = false
branch = "trunk"

[paths]
exclude = ["one"]
include = ["two"]

[lfs]
patterns = []

[hooks]
source = ""
ref = ""
""")
    config = Config.load(tmp_path)
    assert config.auto_pull_on_start is False
    assert config.branch == "trunk"
    assert "one" in config.excludes
    assert "logs_*.sqlite*" in config.excludes
    assert "sessions/" not in config.excludes
    assert config.includes == ["two"]
    assert not config.lfs_patterns
    assert config.hooks_source == ""


def test_load_rejects_malformed_toml(tmp_path: Path) -> None:
    """Verify malformed TOML raises a config error."""
    (tmp_path / ".sync.toml").write_text("[sync")
    with pytest.raises(ConfigError):
        Config.load(tmp_path)


def test_apply_writes_generated_files(tmp_path: Path) -> None:
    """Verify applying config writes generated sync files."""
    Config(hooks_source="", hooks_ref="").apply(tmp_path)
    assert (tmp_path / ".sync.toml").exists()
    assert (
        (tmp_path / ".gitignore")
        .read_text()
        .startswith("# Generated by codex-cli-sync.")
    )
    assert (tmp_path / ".gitattributes").exists()
