"""Configuration loading and generated file rendering."""

from __future__ import annotations

import fnmatch
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from codex_cli_sync.errors import ConfigError

DEFAULT_CODEX_DIR = Path.home() / ".codex"
DEFAULT_HOOK_SOURCE = "git+https://github.com/vanboardman7/codex-cli-sync"
DEFAULT_HOOK_REF = "main"

DEFAULT_EXCLUDES = [
    ".sync.lock",
    ".sync.log",
    ".sync-state.json",
    "auth.json",
    "auth.json.*",
    "*.tmp",
    "*.swp",
    ".DS_Store",
]

DEFAULT_LFS_PATTERNS: list[str] = []


@dataclass
class Config:  # pylint: disable=too-many-instance-attributes
    """Runtime settings for sync behavior and generated files."""

    auto_pull_on_start: bool = True
    auto_push_on_stop: bool = True
    branch: str = "main"
    excludes: list[str] = field(default_factory=lambda: list(DEFAULT_EXCLUDES))
    includes: list[str] = field(default_factory=list)
    lfs_patterns: list[str] = field(default_factory=lambda: list(DEFAULT_LFS_PATTERNS))
    hooks_source: str = DEFAULT_HOOK_SOURCE
    hooks_ref: str = DEFAULT_HOOK_REF

    @classmethod
    def load(cls, codex_dir: Path = DEFAULT_CODEX_DIR) -> "Config":
        """Load sync configuration from disk or return defaults."""
        path = codex_dir / ".sync.toml"
        if not path.exists():
            return cls()
        try:
            data = tomllib.loads(path.read_text())
        except tomllib.TOMLDecodeError as exc:
            raise ConfigError(f"invalid TOML in {path}: {exc}") from exc
        except OSError as exc:
            raise ConfigError(f"cannot read {path}: {exc}") from exc
        return cls.from_dict(data)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Config":
        """Build a config object from parsed TOML data."""
        sync = _table(data, "sync")
        paths = _table(data, "paths")
        lfs = _table(data, "lfs")
        hooks = _table(data, "hooks")
        return cls(
            auto_pull_on_start=_bool(sync, "auto_pull_on_start", True),
            auto_push_on_stop=_bool(sync, "auto_push_on_stop", True),
            branch=_str(sync, "branch", "main"),
            excludes=_str_list(paths, "exclude", DEFAULT_EXCLUDES),
            includes=_str_list(paths, "include", []),
            lfs_patterns=_str_list(lfs, "patterns", DEFAULT_LFS_PATTERNS),
            hooks_source=_str(hooks, "source", DEFAULT_HOOK_SOURCE),
            hooks_ref=_str(hooks, "ref", DEFAULT_HOOK_REF),
        )

    def write_default(self, codex_dir: Path = DEFAULT_CODEX_DIR) -> None:
        """Write the default configuration file when it does not exist."""
        path = codex_dir / ".sync.toml"
        if path.exists():
            return
        codex_dir.mkdir(parents=True, exist_ok=True)
        path.write_text(self.to_toml())

    def to_toml(self) -> str:
        """Render this config as TOML for the sync settings file."""
        excludes = _toml_list(self.excludes)
        includes = _toml_list(self.includes)
        lfs_patterns = _toml_list(self.lfs_patterns)
        return (
            "[sync]\n"
            f"auto_pull_on_start = {_toml_bool(self.auto_pull_on_start)}\n"
            f"auto_push_on_stop = {_toml_bool(self.auto_push_on_stop)}\n"
            f'branch = "{self.branch}"\n\n'
            "[paths]\n"
            f"exclude = {excludes}\n"
            f"include = {includes}\n\n"
            "[lfs]\n"
            f"patterns = {lfs_patterns}\n\n"
            "[hooks]\n"
            f'source = "{self.hooks_source}"\n'
            f'ref = "{self.hooks_ref}"\n'
        )

    def apply(self, codex_dir: Path = DEFAULT_CODEX_DIR) -> None:
        """Write generated sync configuration files into the Codex directory."""
        codex_dir.mkdir(parents=True, exist_ok=True)
        self.write_default(codex_dir)
        (codex_dir / ".gitignore").write_text(self.render_gitignore())
        (codex_dir / ".gitattributes").write_text(self.render_gitattributes())

    def render_gitignore(self) -> str:
        """Render the generated .gitignore content."""
        lines = [
            "# Generated by codex-cli-sync.",
            "# Edit .sync.toml, then run: codex-sync config apply",
            "",
        ]
        lines.extend(self.excludes)
        if self.includes:
            lines.append("")
            lines.extend(f"!{pattern}" for pattern in self.includes)
        return "\n".join(lines).rstrip() + "\n"

    def render_gitattributes(self) -> str:
        """Render optional Git LFS attributes when configured."""
        if not self.lfs_patterns:
            return ""
        lines = [
            "# Generated by codex-cli-sync.",
            "# Files below are good candidates for Git LFS when the repo enables it.",
            "",
        ]
        lines.extend(
            f"{pattern} filter=lfs diff=lfs merge=lfs -text"
            for pattern in self.lfs_patterns
        )
        return "\n".join(lines).rstrip() + "\n"

    def excluded(self, relative_path: str) -> bool:
        """Return whether a relative path should be excluded from sync."""
        path = relative_path.replace("\\", "/")
        if any(fnmatch.fnmatch(path, pattern) for pattern in self.includes):
            return False
        return any(fnmatch.fnmatch(path, pattern) for pattern in self.excludes)


def _table(data: dict[str, Any], key: str) -> dict[str, Any]:
    value = data.get(key, {})
    if not isinstance(value, dict):
        raise ConfigError(f"[{key}] must be a table")
    return value


def _bool(data: dict[str, Any], key: str, default: bool) -> bool:
    value = data.get(key, default)
    if not isinstance(value, bool):
        raise ConfigError(f"{key} must be true or false")
    return value


def _str(data: dict[str, Any], key: str, default: str) -> str:
    value = data.get(key, default)
    if not isinstance(value, str):
        raise ConfigError(f"{key} must be a string")
    return value


def _str_list(data: dict[str, Any], key: str, default: list[str]) -> list[str]:
    value = data.get(key, default)
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise ConfigError(f"{key} must be a list of strings")
    return list(value)


def _toml_bool(value: bool) -> str:
    return "true" if value else "false"


def _toml_list(values: list[str]) -> str:
    return "[" + ", ".join(f'"{value}"' for value in values) + "]"
